environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
install:
  - ps: Install-Product node $env:nodejs_version
  - cinst googlechrome
  - cinst selenium-chrome-driver
  - npm install
test_script:
  - npm test
build: off
