language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: eGBVKgHgj+w3C1UQLZN+l1Iqf2qp+LDdLyEeWcum0OFdVkS5bDL7iLhnhs74U/iEoF353ITPspA6FSmbN8VyurkNo5arMwvIsJIc+YzujMUj+TL4WUFpNXHmRtGHJFR7vVaiTeoL13cIiDKfEH5fTnRC6vCV3lqA/2YAQMktsTCET+3tv7HEGzimKN9/NaxaM1/yT/fF5ZBirUgCX20jVVv+CBsTcF/ekJE4fKPxvq07qRYG4V/6xCIbQD2GLKOf/Yv3Udra54iKKVQLTjeLTQSS8ShAkE0QZ01kp9CP4p7ysAIHSoyx5csyLISgvv6BGqY0IkpEeTUpjMtwmQBsJ97ZLpyirnevisSIwIpTxtufHeM1Sng6J2lSvXvjvM18ZlfgOzYuVXlf8y2ovyJip+Tv16B4LvAxZKHS7SQM4AZ+BoUqWrKo0x59yLgN0fwwsj/G96sXiqjIswOxvZ8GUmBsv/D6g6wqSqFBaRR83x4gN3uWEYRS1wi1kbaruv4RH64pToXUlDXoOCY0wMqgroT9/V+9ZqOfI7FJI34DhJQR7/P1nWKuJNNRxs9hZcaTEJiNRzxrdVMxsAus3h9YArThl00z+QgWtIRT57d7xHiNokBnI7MdvLRHZhxgvNc0icNoQ3/I9Z2kmABqBceISKVXnj8JQTeYG0oai4HOO28=
  on:
    tags: true
    repo: kei-ito/sable
