language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
- npm install -g nyc eslint
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: eGBVKgHgj+w3C1UQLZN+l1Iqf2qp+LDdLyEeWcum0OFdVkS5bDL7iLhnhs74U/iEoF353ITPspA6FSmbN8VyurkNo5arMwvIsJIc+YzujMUj+TL4WUFpNXHmRtGHJFR7vVaiTeoL13cIiDKfEH5fTnRC6vCV3lqA/2YAQMktsTCET+3tv7HEGzimKN9/NaxaM1/yT/fF5ZBirUgCX20jVVv+CBsTcF/ekJE4fKPxvq07qRYG4V/6xCIbQD2GLKOf/Yv3Udra54iKKVQLTjeLTQSS8ShAkE0QZ01kp9CP4p7ysAIHSoyx5csyLISgvv6BGqY0IkpEeTUpjMtwmQBsJ97ZLpyirnevisSIwIpTxtufHeM1Sng6J2lSvXvjvM18ZlfgOzYuVXlf8y2ovyJip+Tv16B4LvAxZKHS7SQM4AZ+BoUqWrKo0x59yLgN0fwwsj/G96sXiqjIswOxvZ8GUmBsv/D6g6wqSqFBaRR83x4gN3uWEYRS1wi1kbaruv4RH64pToXUlDXoOCY0wMqgroT9/V+9ZqOfI7FJI34DhJQR7/P1nWKuJNNRxs9hZcaTEJiNRzxrdVMxsAus3h9YArThl00z+QgWtIRT57d7xHiNokBnI7MdvLRHZhxgvNc0icNoQ3/I9Z2kmABqBceISKVXnj8JQTeYG0oai4HOO28=
  on:
    tags: true
    repo: kei-ito/sable
env:
  global:
  - secure: szz48ASduJMBxpxJkNpwQsT/xQVez7diCLK+N89m9VJBfVREj+tfnEZotYUH3qNfUaXOI8k+CtA6GuGLxq+axQo/v8FtbgeTZFaibvbW9qp57fkgU1ChS1YWLdZhejFkI7eqtPS9d5j+0CRIJc0fXzX3wdHONjA0fsF2Iql1XW3gGaCsMkETLKycF7VCOsrXgvHzS97gueWJRnrM4AlZGlogsXtttab+Jeai1scydDGny3bk1QFI+gYcoew3A1RyMkZCZbIe75OsMTRyXoCW6x9z9pzqjFonpFn+Gm093zrYw1NPh2isMzoodWOCsRr+W0KKW5FehQoJrnABvHukJSpo5YeREf00Lp7MbyRz9ExHZiBQKsOdDbMXN+q/oH7hwRBSUbBQdFdnasvfizgkOqXS7xJ60MeABeUghbKiyNhRTiLgFSOuHR3EhcuLTwYOLdCJjxcA34Xek+DasdLkrRVXGeV+UvVVlNV80BD0k4/1Ng7I1pZcIS+BPNhsUdzfv2HTLD3z5mXUmLrl0Z/fMZtFfhjYk228xhQCZCFBfpJPrVNFbwNZX8IfY2/qebI3s3okqTZ+a/OEqeHbAOzu7gPfhOw+X3T1bYuUEL7bW91Bep7H1fVJntGvdleNUxlmOZS+v6ZYFS91CvA+J1X3Gf1rb4pliTn8HbIsXP+NIK4=
  - secure: fBGmcmr5fPO/8wXUJh1w9eNfHdG9Y4gnEaAhF1By9NyCprwv1RKgG8nVtH9AlTnH87k9imspXJm6oi//o1tfxPirGPPzMXLy1Dls7SaIdfJ4gFTJoM06sXkqx13FrBR6EuqYqR/ZV/E2hLXbdRdyvj6GdXIlcIhA7tqolOXISGzyti1uq1FhnReXXJEn3Em8m6w0O7uCV7GxhNzfIqShlLneIL1w7coW+yiRcQmKCrR2w3x0aQu134cfjx9YtyP4olPkzR1+OyaXJSHPArA7PIcS8dcBJuVkuBrtgRvG31o8q5KsTNkKGFAAf60vn38ZtTbGfrgNhJp02zknXJL0hgCOicshu4CXoNmoNWev8QyHnUg9lEoUrtw47TMeqgKsw8urENwPXOriaeJtaUgd/H9ixkivEkIxddWp9wJb+kWJhwC9cbRVLuTKkKDczboRScBMI7XgVdifAGhQy+V5dl58uW6W4Pp1QKDKUtNHI6pEF6HEQpY6grcha/rcSreIiY2iz7HqegNOo7MBhyHV8CPTm1q28HLuOSGU5wtCjc/U/kfM3mAFDDro+L6JtorARrWRf/momSUr2eWBgcQdRBKCCM9SestPChJBsv+vg441bpKtX4Ksq3vialWELEBjrbVEztGmB+y1FUXh31oqwvoqW8f2C1CDXocrWH0ho/E=
