language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
script:
- npm run test_coverage
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: iPi9ljiYY/RO4EMVvRN6QfL2MEoEop7n1rs2tTtPpjJwirb3HKEmGPZEozxBagshcbRELgFMZihjJrSTUOdmOrFPpkBDQJuXu03Q2qvz8/ne1ISLbOjyuoT58Qe/vkS8XPv+LFB9CW3YmWuUpHZN6vVkwefH0ulC75ytFV8jkoWET6ULAEZeYCWUaVUmtMkAe6htIWHyYhCFeu2ayGRTmtFvoVOydAKYU8BsmEhZM7liZEBAervCnZwGF3LW3P9Ap2x3FRQ+9JNUPxN4JsEnLiqlvX9jRnUx/yRypeHRNuqkvqEB3aQAqfMb9AWDwLNf0KT9kx4njAt0SVaNehYZuzRHTRSZ5mJyWknTPuBxk7gertLVYknsynoi4DKfYRxTlHQkpzyxQQ4tYmKU9dYma6CcQ5vdU8FUNV2QsALDsLD//vnNgXLSp4plU5HUIa6MzubmvOicGlPOvya0G+sKLwv09jujVWwktkBTeaQ9Y0QihdWyyTCQMchyV25Z2oUXLdXKkAVS04md6XMPDz4hju0MmrWmZf+saSfpqtOIEneDT0ALeMEq5Q0BMno0jzQjNVQjztIFI/CkTMd2pKMKxX039I6Mkc9jiNQh1g93/MASgv9fzJzyyVmzjxQDKkJgWw/r/pptSS6ZgwjaW3n1ig0iUu+WFGMaMOt98W19AJw=
  on:
    tags: true
    repo: kei-ito/sable
    branch: master
notifications:
  slack:
    secure: DXNfW/BODt7dvAka2rcLUS2ogNai+ZUWqn7Q7wKgilMZ/vAR2dNS0HmD0NB6Tf7LZq7QgdEuvskHce2blKNAzseeTgPkaVzo+T4B6gl/+A2fRjddKbvDMriFgf1+JmeQ2gfm7Q6gIsF/IlyS5HsFWjytyR5dy/qc9liYknuiq8IKq8IGx2PbV6XUrJF7Qw3zdXfbkaTmW8288azqRQvYaoEY/oQvaxtIl7xFW2T4lqk8i3nUopemBPHqmZJXVnX11bm+S6BGXWyAc+5gPF3Mk/STI7vrBwble5T/w3qIiqP2wLjVCwiJitl0DTFel0cOVGDSHAffm90jMBP0vY2djt4FsXg+6uBOduHmCxqGLglpp6bR4c8E1R75e7omIaXX0FSAT3pdDtYxDPtBiHUfho+aVKd31K6KlaEqYo3BDpOUHyerl+XYMvPlpgFk+uKuVdRn0rJ7riY1xP8vJcRK6gXHgwad+thTTl3rkYUbY46n+Ahr2sNuqZnJIbwMLdoxZugUYsRl9MzzgwExwnPkA7mCrUA4UwjED+oZKGle0ajvvN074ygaGnuPYhGttx3f44pv36IlJ1hOiR90y5081e94dL2Rvrj4i+IgtvxJzcabZ7t/ODbGYwL2BDPCF0Q73njbUCaV4DlwLvFQBpv1iSuBT8GQwLFAGRoyk9lgehY=
env:
  BROWSERSTACK_USERNAME:
    secure: puWE5Y5sFrfW3OerKLctwpJxBBJz7JYHwRlaKT+tHGzlMgWpUgQ+IPb4An+FDKxsbnNKqj9cvV7mZvGSnBkhR9WwYGWJKEPjcFa5K1CTahngJxUHPv5mQzrlSljHk1rwhzyNGIHKwoShrh7NjzUoPS+7RM8sNQ6P8grtOvJfd/0SEAQg63WpugCbPBWQ/+9gqCWVPzgvSV2tHxP8YGeqDBGsIq2P5cJ83D16FAUF2H1u4fSolW5/iFVKQDj/r3Eir6a6mdkwsa5+ZC5+LWLTbIaQF1oLgXXbvJN7cIrCVdxxME+3y5nvvTJY6n5G+hhDzsqphbFp/jyIdA2/Ck77Sh688v+NsYq2i7C/lLC3rE3kh5H4/ocuof6Cp031PyoG+weCmA67yipp4Y9n2P19/qWmFtfkxsdvd08DIbP32xwOrIwrkvLTOIGY3dII34V5sS5aAmUtaGEuSsf4m4OwXhtRxc6KpmmbkmUNW417cgaS+Fa4gtG5XyAFJ7P7yMy//92hYXAUEnqRGOWqFtG1bX/q5MUwUd7l8/94F/7t5UEV54Ja/XbKRcyYg/jOXJZMTyJ01JI4EYNXo+2VL104StMWykYgjCk1TADLBDmAVgdI+MG1U5YHMQZIxUX/rN8L8m9BDy3GzqEPaKCUSY662S6V3LMIWlN0GzDFL5o/9y0=
  global:
  - secure: szz48ASduJMBxpxJkNpwQsT/xQVez7diCLK+N89m9VJBfVREj+tfnEZotYUH3qNfUaXOI8k+CtA6GuGLxq+axQo/v8FtbgeTZFaibvbW9qp57fkgU1ChS1YWLdZhejFkI7eqtPS9d5j+0CRIJc0fXzX3wdHONjA0fsF2Iql1XW3gGaCsMkETLKycF7VCOsrXgvHzS97gueWJRnrM4AlZGlogsXtttab+Jeai1scydDGny3bk1QFI+gYcoew3A1RyMkZCZbIe75OsMTRyXoCW6x9z9pzqjFonpFn+Gm093zrYw1NPh2isMzoodWOCsRr+W0KKW5FehQoJrnABvHukJSpo5YeREf00Lp7MbyRz9ExHZiBQKsOdDbMXN+q/oH7hwRBSUbBQdFdnasvfizgkOqXS7xJ60MeABeUghbKiyNhRTiLgFSOuHR3EhcuLTwYOLdCJjxcA34Xek+DasdLkrRVXGeV+UvVVlNV80BD0k4/1Ng7I1pZcIS+BPNhsUdzfv2HTLD3z5mXUmLrl0Z/fMZtFfhjYk228xhQCZCFBfpJPrVNFbwNZX8IfY2/qebI3s3okqTZ+a/OEqeHbAOzu7gPfhOw+X3T1bYuUEL7bW91Bep7H1fVJntGvdleNUxlmOZS+v6ZYFS91CvA+J1X3Gf1rb4pliTn8HbIsXP+NIK4=
  - secure: fBGmcmr5fPO/8wXUJh1w9eNfHdG9Y4gnEaAhF1By9NyCprwv1RKgG8nVtH9AlTnH87k9imspXJm6oi//o1tfxPirGPPzMXLy1Dls7SaIdfJ4gFTJoM06sXkqx13FrBR6EuqYqR/ZV/E2hLXbdRdyvj6GdXIlcIhA7tqolOXISGzyti1uq1FhnReXXJEn3Em8m6w0O7uCV7GxhNzfIqShlLneIL1w7coW+yiRcQmKCrR2w3x0aQu134cfjx9YtyP4olPkzR1+OyaXJSHPArA7PIcS8dcBJuVkuBrtgRvG31o8q5KsTNkKGFAAf60vn38ZtTbGfrgNhJp02zknXJL0hgCOicshu4CXoNmoNWev8QyHnUg9lEoUrtw47TMeqgKsw8urENwPXOriaeJtaUgd/H9ixkivEkIxddWp9wJb+kWJhwC9cbRVLuTKkKDczboRScBMI7XgVdifAGhQy+V5dl58uW6W4Pp1QKDKUtNHI6pEF6HEQpY6grcha/rcSreIiY2iz7HqegNOo7MBhyHV8CPTm1q28HLuOSGU5wtCjc/U/kfM3mAFDDro+L6JtorARrWRf/momSUr2eWBgcQdRBKCCM9SestPChJBsv+vg441bpKtX4Ksq3vialWELEBjrbVEztGmB+y1FUXh31oqwvoqW8f2C1CDXocrWH0ho/E=
