language: node_js
node_js:
- '7'
script: npm run test_coverage
after_success:
- npm install codacy-coverage
- cat ./coverage/lcov.info | ./node_modules/codacy-coverage/bin/codacy-coverage.js
  --debug
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: iPi9ljiYY/RO4EMVvRN6QfL2MEoEop7n1rs2tTtPpjJwirb3HKEmGPZEozxBagshcbRELgFMZihjJrSTUOdmOrFPpkBDQJuXu03Q2qvz8/ne1ISLbOjyuoT58Qe/vkS8XPv+LFB9CW3YmWuUpHZN6vVkwefH0ulC75ytFV8jkoWET6ULAEZeYCWUaVUmtMkAe6htIWHyYhCFeu2ayGRTmtFvoVOydAKYU8BsmEhZM7liZEBAervCnZwGF3LW3P9Ap2x3FRQ+9JNUPxN4JsEnLiqlvX9jRnUx/yRypeHRNuqkvqEB3aQAqfMb9AWDwLNf0KT9kx4njAt0SVaNehYZuzRHTRSZ5mJyWknTPuBxk7gertLVYknsynoi4DKfYRxTlHQkpzyxQQ4tYmKU9dYma6CcQ5vdU8FUNV2QsALDsLD//vnNgXLSp4plU5HUIa6MzubmvOicGlPOvya0G+sKLwv09jujVWwktkBTeaQ9Y0QihdWyyTCQMchyV25Z2oUXLdXKkAVS04md6XMPDz4hju0MmrWmZf+saSfpqtOIEneDT0ALeMEq5Q0BMno0jzQjNVQjztIFI/CkTMd2pKMKxX039I6Mkc9jiNQh1g93/MASgv9fzJzyyVmzjxQDKkJgWw/r/pptSS6ZgwjaW3n1ig0iUu+WFGMaMOt98W19AJw=
  on:
    tags: true
    repo: kei-ito/sable
    branch: master
notifications:
  slack:
    secure: DXNfW/BODt7dvAka2rcLUS2ogNai+ZUWqn7Q7wKgilMZ/vAR2dNS0HmD0NB6Tf7LZq7QgdEuvskHce2blKNAzseeTgPkaVzo+T4B6gl/+A2fRjddKbvDMriFgf1+JmeQ2gfm7Q6gIsF/IlyS5HsFWjytyR5dy/qc9liYknuiq8IKq8IGx2PbV6XUrJF7Qw3zdXfbkaTmW8288azqRQvYaoEY/oQvaxtIl7xFW2T4lqk8i3nUopemBPHqmZJXVnX11bm+S6BGXWyAc+5gPF3Mk/STI7vrBwble5T/w3qIiqP2wLjVCwiJitl0DTFel0cOVGDSHAffm90jMBP0vY2djt4FsXg+6uBOduHmCxqGLglpp6bR4c8E1R75e7omIaXX0FSAT3pdDtYxDPtBiHUfho+aVKd31K6KlaEqYo3BDpOUHyerl+XYMvPlpgFk+uKuVdRn0rJ7riY1xP8vJcRK6gXHgwad+thTTl3rkYUbY46n+Ahr2sNuqZnJIbwMLdoxZugUYsRl9MzzgwExwnPkA7mCrUA4UwjED+oZKGle0ajvvN074ygaGnuPYhGttx3f44pv36IlJ1hOiR90y5081e94dL2Rvrj4i+IgtvxJzcabZ7t/ODbGYwL2BDPCF0Q73njbUCaV4DlwLvFQBpv1iSuBT8GQwLFAGRoyk9lgehY=
env:
  global:
    secure: C+1SgM8JUkeClxGsZL9uvxBHikRnD+5EKRRWPRIJTJE9d1BxDoi8HvZHibdiPwishsmpatGp67FL+dthNEa5AYLJSLEl+BT/UIz3wdHlydokkQ8s4pqurZ2ssB3VJ+Pe3JsnthXzkBOlbtwCfvNsVeozXtJX556rZjnRO+/XnUca9JqmrXoLeCq+7jfdZHDs7VTAtQ80K3955CGmzluDyqnqKLk686XD1qIgFHfgnUvmJYMMaUHCFKWz+EmHdNn7hKg+edgDSbDLGaJ3YO75rKDDckqKwjYGYbquoxP5M1N5BgeceDacz55fdnsWkTcqAFoZ+H6ZA/MMAZthwzetQTbM0e7hUdzcLU7+ES70gDHVCZmA5FJPZEK0JseXCNQT7dNTPv5ltjGUYpyiGa1GOUwta329mhuX54ZGHfFEsDimO5HVbNjJuAfQpxt7Eav7iapIXIMthhgxoL9qeMTuxER4k/wGAofAt0UpH4RrdcSr7TRbas3qIMT6O24XDwduWw55fvvcj3FVDJ3HMwxJYpQtWyZP8NqiscVHZt+gwwYS5pC1g6vBF/pEaZOm22Hz1/SwQiZt2J7j119sq887vDmgepLIIT7kr+6fHWmQaiuWXlUNKNbcvkYuwk2Eaz/eLu3yyWY/6NvaakddTH4s12X6qU4cSojE7JvFk/xVAjY=
