language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
install:
- npm install
- npm install -g nyc eslint
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: eGBVKgHgj+w3C1UQLZN+l1Iqf2qp+LDdLyEeWcum0OFdVkS5bDL7iLhnhs74U/iEoF353ITPspA6FSmbN8VyurkNo5arMwvIsJIc+YzujMUj+TL4WUFpNXHmRtGHJFR7vVaiTeoL13cIiDKfEH5fTnRC6vCV3lqA/2YAQMktsTCET+3tv7HEGzimKN9/NaxaM1/yT/fF5ZBirUgCX20jVVv+CBsTcF/ekJE4fKPxvq07qRYG4V/6xCIbQD2GLKOf/Yv3Udra54iKKVQLTjeLTQSS8ShAkE0QZ01kp9CP4p7ysAIHSoyx5csyLISgvv6BGqY0IkpEeTUpjMtwmQBsJ97ZLpyirnevisSIwIpTxtufHeM1Sng6J2lSvXvjvM18ZlfgOzYuVXlf8y2ovyJip+Tv16B4LvAxZKHS7SQM4AZ+BoUqWrKo0x59yLgN0fwwsj/G96sXiqjIswOxvZ8GUmBsv/D6g6wqSqFBaRR83x4gN3uWEYRS1wi1kbaruv4RH64pToXUlDXoOCY0wMqgroT9/V+9ZqOfI7FJI34DhJQR7/P1nWKuJNNRxs9hZcaTEJiNRzxrdVMxsAus3h9YArThl00z+QgWtIRT57d7xHiNokBnI7MdvLRHZhxgvNc0icNoQ3/I9Z2kmABqBceISKVXnj8JQTeYG0oai4HOO28=
  on:
    tags: true
    repo: kei-ito/sable
env:
  global:
  - secure: HhZPVIxp6QJ/djXL+VBUVdGbPg0bjydthHcJ3Qd1vX8m8PuzDQfl/Fuo/yqvyDpN7PDu0JndNdb0bbOGxyPP/nqeajGAnNnTsMI0g0+5u50LTAJSpYaVPZ0H2y9YHDmZdk8fYA31RSzTTqPYRZj5ONVQNs9yQVCY1AsXUB/SLeQt12VFASeWiWyOa7d0LeWF/KEjOIioNOZgl2BdBLGVgf8lu84HvTChXfOQX3nsEPQaSBdnwmOHCIr5bCq2gAd7mH9bUvHlFDxCoS6SDvDYRdw4AuwmhXOtl2/8c1B/fpu0xwtw6kvcxRZuj24RXkUEASXdE8qR2+j7hTprbZ+RLPcOTwMwylXP7KfPIR3sAYdMxJOKhW67/XtMJLWbaHN3c9+YM2jW8dckFeBde2qKRkALJOQwf41BFM0sj/UUXHLYYBmqhjLt4RJ2DlD6YAAS0CsSjhx8ixjuwMTlmtxZue0bPUnZ8QdDBXf3L/v+dUxSLWidrz9lFbbZWJDCcLXl/r02tMgisPz/NGg6CjW81hJcxh7Ozq9wrLZR7J+tyMp7WGU4XaEnPvd4i+yeo8h3Vt7qJixxxo5CvS9kFEiJPwZLfOZEN4rWjb9p9JBLswW0koDQ/zKGtlS7J0ZBdXcGFFMTnCJykK00LOLUFd2/uv0HsaSSYRGDPEMD5oEdVbw=
  - secure: Q2wIP+DmTbb/Gb4j9qV2tiiRrosFo/0K6G4HibEhrCN2FT5PngvmqIQZGXrofujUHUHSxDEICQlQ/27etvrtEi837a/10v+KAkEAclW3lUnNuk9HZ+NxHNYSJXC5xg1BuglS5oz0qMcSB7Z5j0pMEv0RsyGjE+m18mIqOSfFDo4gDpaZpbX8uztaS1WJK6L0cfuoP2U/wfUV9tSI8bQ7kRj7HGEPjICX5jUUnZ+pDdTKNKHp5LB+BVfE+szVBdA0ypQ73zAbS1AwPweWburjOoK3kp2d58XexDrR+JPkoP/JrUZgxI4USrNm9Zp8HWnm1NH3vLUYN0fC+E8XPuJ2L44yFvIksxZ3pXLMsQWeNoqKeC5+7/omVOHsYraq7qxXnG8W3pdPSYtqLcyR7ebAYeSB196w13rPJ1DS4JlMatoll6CnZG6EPFjNWLvWZ47ykVj6KSYYtJMJmpNnamY7vnTFXCESTKE4TEz5pWKYbQ7wBCMgpoCcqYxGvp6DIH7DweaDT2ze1emZiXaJadJkhTl+n1tz3J9IAIXjcDqG45dgngW6HWM9J3cst40VTYzyCS2jJ/l2rPwjacOjCjUw/Uy433yFsoFGNmILZJZy53BMOC7VirXqeFomp8sg5gvZHW4tv/tnVyusIW4TfLgap4CRjQ9PeoYEKmJKLC5nC0U=
